KUSANAGI_TYPE=wp
KUSANAGI_FQDN=kusanagi.tsplus.asahi.co.jp
KUSANAGI_DIR=/home/kusanagi/core
KUSANAGI_DBNAME=core
KUSANAGI_DBUSER=core
KUSANAGI_DBPASS=dotcaerux
WPLANG=ja
OPT_WOO=
OPT_FORCE_WWW=
KUSANAGI_MARIADB=yes
KUSANAGI_PSQL=no
